name: Test
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"

      - name: Run tests
        run: |
          cd auth && go test . && cd ..
          cd receipt && go test . && cd ..